### ISSUE TITLE
errno = Operation not permitted

### ISSUE THREAD

**Issue by tomasalves8** [drudge/n8n-nodes-puppeteer#37]
When running the node using the docker file I get the following error.
![image](https://github.com/user-attachments/assets/fca0b9b0-44c7-40a7-8959-92988cff1bdc)

Error:
Failed to launch the browser process! Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted [55:55:1209/101635.594608:FATAL:zygote_host_impl_linux.cc(207)] Check failed: . : Operation not permitted (1) [1209/101635.607379:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38) [1209/101635.607508:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38) [1209/101635.607846:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2) [1209/101635.607866:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2) TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by drudge** [comment]
Hi @tomasalves8 - Can you please share the docker log that went with this run? It should have a header with diagnostic version information that I can use to help you.

**Comment by drudge** [comment]
Closing this one. If you're still having issues, please create a new issue with your docker container logs.

**Comment by citizenfish** [comment]
I am seeing this issue:-

```
n8n-puppeteer  | [license SDK] cert is invalid because it has expired
n8n-puppeteer  | Failed to launch/connect to browser: Failed to launch the browser process!
n8n-puppeteer  | Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
n8n-puppeteer  | [44:44:0307/111605.374843:FATAL:zygote_host_impl_linux.cc(206)] Check failed: . : Operation not permitted (1)
n8n-puppeteer  | [0307/111605.382620:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38)
n8n-puppeteer  | [0307/111605.382703:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38)
```

My build process was:-

```
docker build -t n8n-puppeteer -f docker/Dockerfile docker/ --platform linux/amd64
```

Docker Compose

```
services:
  n8n:
    image: n8n-puppeteer
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=roamie_n8n
      - DB_POSTGRESDB_HOST=172.16.0.170
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=roamie_n8n
      - DB_POSTGRESDB_SCHEMA=n8n_workflow
      - DB_POSTGRESDB_PASSWORD=wibble55
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

```

**Comment by loureirorg** [comment]
I fixed this issue by adding the `SYS_ADMIN` capability to the Docker container. This allows Chromium to create the necessary namespaces for its sandbox.

In your `docker-compose.yml`, add this to the n8n service:

```yaml
cap_add:
  - SYS_ADMIN
shm_size: '2gb'
```

The `shm_size` is also recommended to prevent shared memory issues with Chromium. After making this change, restart the container with `docker compose up -d --force-recreate` and the Puppeteer node should work without the namespace errors. 

**Example:**

```yaml
n8n:
  <<: *shared
  build:
    context: .
    dockerfile: Dockerfile
  container_name: n8n
  ports:
    - 5678:5678
  cap_add:
    - SYS_ADMIN
  shm_size: '2gb'
```

Hope this helps!
