### ISSUE TITLE
Recommended installation doesn't correct

### ISSUE THREAD

**Issue by GGM141** [drudge/n8n-nodes-puppeteer#39]
I did installation as decribed in "Community Nodes (Recommended)".
I am using docker-compose from their site
After installation I tried to receive html page. No success.

Error: Could not find Chrome (ver. 131.0.6778.69). This can occur if either 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or 2. your cache path is incorrectly configured (which is: /home/node/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at ChromeLauncher.resolveExecutablePath (/home/node/.n8n/nodes/node_modules/puppeteer-core/src/node/BrowserLauncher.ts:456:16) at ChromeLauncher.executablePath (/home/node/.n8n/nodes/node_modules/puppeteer-core/src/node/ChromeLauncher.ts:276:6) at ChromeLauncher.computeLaunchArguments (/home/node/.n8n/nodes/node_modules/puppeteer-core/src/node/ChromeLauncher.ts:126:26) at ChromeLauncher.launch (/home/node/.n8n/nodes/node_modules/puppeteer-core/src/node/BrowserLauncher.ts:70:14) at PuppeteerExtra.launch (/home/node/.n8n/nodes/node_modules/puppeteer-extra/src/index.ts:169:21) at ExecuteContext.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-puppeteer/nodes/Puppeteer/Puppeteer.node.ts:246:4) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:732:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:716:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1147:20

**Comment by AnirudhG07** [comment]
I am facing the same issue 
I am using docker-compose to use n8n in MacOS.
```
version: "3.8"
services:
  n8n:
    image: n8nio/n8n:1.70.4
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_images:/home/node/.n8n/images
    restart: unless-stopped

volumes:
  n8n_data:
  n8n_images:
```
Please help on this!
